display_one = ord('A')
display_two = ord('B')
display_three = ord('C')
display_four = ord('D')
display_five = ord('b')
display_six = ord('c')
display_seven = ord('d')
display_eight = ord('0')
display_nine = ord('1')
display_ten = ord('2')
display_eleven = ord('$')
display_twelve = ord('*')
display_thirteen = ord('+')

print(display_one)
print(display_two)
print(display_three)
print(display_four)
print(display_five)
print(display_six)
print(display_seven)
print(display_eight)
print(display_nine)
print(display_ten)
print(display_eleven)
print(display_twelve)
print(display_thirteen)